# Testing a CNN with the dataset

This code is used to test a CNN and some image preprocessing utilities with Keras

In [1]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
import glob
import PIL
import PIL.Image
import glob
import pathlib
import matplotlib.pyplot as plt
import rasterio

from tensorflow.keras import layers
import tensorflow_addons as tfa

c:\Users\Kostas\anaconda3\envs\vit\lib\site-packages\scipy\__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.4
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


In [2]:
dataset_dir = pathlib.Path(r"C:\Users\Kostas\Desktop\GIMA\Module_7\Data\filtered_patches_GEE")

## Imports and display

In [3]:
def load_tiff_image(image_path):
    with rasterio.open(image_path) as src:
        return src.read()

In [4]:
import os

base_dir = dataset_dir
class_dirs = [d for d in os.listdir(base_dir) if os.path.isdir(os.path.join(base_dir, d))]

images = []
labels = []
for class_id in class_dirs:
    image_files = [f for f in os.listdir(os.path.join(base_dir, class_id)) if f.endswith('.tif')]
    for f in image_files:
        images.append(load_tiff_image(os.path.join(base_dir, class_id, f)))
        labels.append(int(class_id))

In [5]:
def check_shape(image_path):
    with rasterio.open(image_path) as src:
        return src.shape


In [6]:
import os

# Check if all files have a square shape
base_dir = dataset_dir
class_dirs = [d for d in os.listdir(base_dir) if os.path.isdir(os.path.join(base_dir, d))]

shapes = []
images = []
labels = []
for class_id in class_dirs:
    image_files = [f for f in os.listdir(os.path.join(base_dir, class_id)) if f.endswith('.tif')]
    print(len(image_files))
    for f in image_files:
        shapes.append(check_shape(os.path.join(base_dir, class_id, f)))
        labels.append(int(class_id))
        images.append(load_tiff_image(os.path.join(base_dir, class_id, f)))
        # break

0
205
0
0
0
0
0
42
0


In [7]:
print(shapes[0])
print(labels[0])
print(images[0])

(134, 134)
11
[[[0.         0.         0.         ... 0.         0.         0.        ]
  [0.         0.03274167 0.039275   ... 0.032975   0.03308333 0.03385   ]
  [0.         0.03471667 0.03670833 ... 0.032175   0.033575   0.033975  ]
  ...
  [0.         0.0205     0.020775   ... 0.036375   0.03685    0.03986667]
  [0.         0.0204     0.020375   ... 0.032175   0.0369     0.04381667]
  [0.         0.02055833 0.02010833 ... 0.03374167 0.03448333 0.03670833]]

 [[0.         0.         0.         ... 0.         0.         0.        ]
  [0.         0.03810833 0.04368334 ... 0.03916667 0.0387     0.03691667]
  [0.         0.04585833 0.04253333 ... 0.04055833 0.042      0.04299167]
  ...
  [0.         0.02285    0.022325   ... 0.037225   0.04310833 0.043225  ]
  [0.         0.02264167 0.022175   ... 0.03406667 0.05385    0.04980833]
  [0.         0.02259167 0.02220833 ... 0.03575    0.04779167 0.0398    ]]

 [[0.         0.         0.         ... 0.         0.         0.        ]
  [0.   

In [19]:
images = [(image - np.min(image)) / (np.max(image) - np.min(image)) for image in images]

In [21]:
tf.keras.utils.pad_sequences(
    images,
    maxlen=None,
    dtype='int32',
    padding='pre',
    truncating='pre',
    value=1000
)

array([[[[          0,           0,           0, ...,           0,
                    0,           0],
         [          0,           0,           0, ...,           0,
                    0,           0],
         [          0,           0,           0, ...,           0,
                    0,           0],
         ...,
         [          0,           0,           0, ...,           0,
                    0,           0],
         [          0,           0,           0, ...,           0,
                    0,           0],
         [          0,           0,           0, ...,           0,
                    0,           0]],

        [[          0,           0,           0, ...,           0,
                    0,           0],
         [          0,           0,           0, ...,           0,
                    0,           0],
         [          0,           0,           0, ...,           0,
                    0,           0],
         ...,
         [          0,           0

In [22]:
image_dataset = tf.data.Dataset.from_tensor_slices(images) 
label_dataset = tf.data.Dataset.from_tensor_slices(labels) 
dataset = tf.data.Dataset.zip((image_dataset, label_dataset)) # Zipped together. They are a tuple

In [23]:
# Accessing elements of a dataset
for z in label_dataset:
    print(z.numpy())
    break
    

11


In [39]:
for i in image_dataset:
    print(i.numpy())
    break

[[[0.         0.         0.         ... 0.         0.         0.        ]
  [0.         0.054235   0.06505715 ... 0.0546215  0.05480095 0.0560709 ]
  [0.         0.05750649 0.06080559 ... 0.05329634 0.05561537 0.05627796]
  ...
  [0.         0.03395727 0.03441279 ... 0.06025344 0.06104026 0.06603722]
  [0.         0.03379162 0.03375021 ... 0.05329634 0.06112307 0.0725802 ]
  [0.         0.03405389 0.03330849 ... 0.05589145 0.05711998 0.06080559]]

 [[0.         0.         0.         ... 0.         0.         0.        ]
  [0.         0.06312463 0.07235935 ... 0.0648777  0.06410469 0.06115068]
  [0.         0.07596213 0.07045443 ... 0.06718293 0.06957098 0.07121363]
  ...
  [0.         0.03784993 0.03698029 ... 0.06166142 0.07140688 0.07160014]
  [0.         0.03750483 0.03673182 ... 0.0564298  0.08919994 0.08250511]
  [0.         0.03742201 0.03678704 ... 0.05921816 0.0791646  0.06592678]]

 [[0.         0.         0.         ... 0.         0.         0.        ]
  [0.         0.083678

In [24]:
# Check the specs of the dataset
dataset.element_spec

(TensorSpec(shape=(12, 134, 134), dtype=tf.float32, name=None),
 TensorSpec(shape=(), dtype=tf.int32, name=None))

In [30]:
model = keras.Sequential([
    keras.layers.Conv2D(32, (3, 3), activation='relu', input_shape=(32, 134, 134, 12)),
    keras.layers.MaxPooling2D((2, 2)),
    keras.layers.Flatten(),
    keras.layers.Dense(10, activation='softmax')
])

ValueError: Input 0 of layer "max_pooling2d_4" is incompatible with the layer: expected ndim=4, found ndim=5. Full shape received: (None, 32, 132, 132, 32)

In [26]:
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [27]:
train_size = int(len(images) * 0.8)  # 80% for training, adjust the split ratio as needed

train_dataset = dataset.take(train_size)
test_dataset = dataset.skip(train_size)

In [28]:
def preprocess_image(image, label):
    # Transpose dimensions: (channels, height, width) -> (height, width, channels)
    image = tf.transpose(image, perm=[1, 2, 0])
    # Apply your preprocessing transformations here
    processed_image = image
    return processed_image, label

train_dataset = train_dataset.map(preprocess_image)
test_dataset = test_dataset.map(preprocess_image)

In [29]:
model.fit(train_dataset, epochs=10)

Epoch 1/10


ValueError: in user code:

    File "c:\Users\Kostas\anaconda3\envs\vit\lib\site-packages\keras\engine\training.py", line 1051, in train_function  *
        return step_function(self, iterator)
    File "c:\Users\Kostas\anaconda3\envs\vit\lib\site-packages\keras\engine\training.py", line 1040, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "c:\Users\Kostas\anaconda3\envs\vit\lib\site-packages\keras\engine\training.py", line 1030, in run_step  **
        outputs = model.train_step(data)
    File "c:\Users\Kostas\anaconda3\envs\vit\lib\site-packages\keras\engine\training.py", line 889, in train_step
        y_pred = self(x, training=True)
    File "c:\Users\Kostas\anaconda3\envs\vit\lib\site-packages\keras\utils\traceback_utils.py", line 67, in error_handler
        raise e.with_traceback(filtered_tb) from None
    File "c:\Users\Kostas\anaconda3\envs\vit\lib\site-packages\keras\engine\input_spec.py", line 264, in assert_input_compatibility
        raise ValueError(f'Input {input_index} of layer "{layer_name}" is '

    ValueError: Input 0 of layer "sequential_3" is incompatible with the layer: expected shape=(None, 134, 134, 12), found shape=(134, 134, 12)


In [ ]:
print(label_dataset.element_spec)

Original guide from keras

In [ ]:
# Importing the dataset

print('Training Data')

train_dataset = tf.keras.preprocessing.image_dataset_from_directory(
    directory=dataset_dir,
    labels="inferred",
    label_mode="int",
    class_names=None,
    color_mode="rgb",
    batch_size=32,
    image_size=(256, 256),
    shuffle=True,
    seed=100,
    validation_split=0.3,
    subset='training',
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False,
)

print('\nValidation Data')

validation_dataset = tf.keras.preprocessing.image_dataset_from_directory(
    directory=dataset_dir,
    labels="inferred",
    label_mode="int",
    class_names=None,
    color_mode="rgb",
    batch_size=32,
    image_size=(256, 256),
    shuffle=True,
    seed=100,
    validation_split=0.3,
    subset='validation',
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False,
)

In [ ]:
print(type(train_dataset))
class_names = train_dataset.class_names # return type: list
print(class_names)
type(class_names)

In [ ]:
# Show some images
plt.figure(figsize=(10, 10))
for images, labels in train_dataset.take(1):
    for i in range(9):
        ax = plt.subplot(3, 3, i +1)
        plt.imshow(images[i].numpy().astype("uint8"))
        plt.title(class_names[labels[i]])
        [plt.axis("off")]

## Building and training the network

In [ ]:
num_classes = len(class_names)

model = tf.keras.Sequential([
  tf.keras.layers.Rescaling(1./255),
  tf.keras.layers.Conv2D(32, 3, activation='relu'),
  tf.keras.layers.MaxPooling2D(),
  tf.keras.layers.Conv2D(32, 3, activation='relu'),
  tf.keras.layers.MaxPooling2D(),
  tf.keras.layers.Conv2D(32, 3, activation='relu'),
  tf.keras.layers.MaxPooling2D(),
  tf.keras.layers.Flatten(),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dense(num_classes)
])

In [ ]:
model.compile(
    optimizer='adam',
    loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    metrics=['accuracy'])

In [ ]:
model.fit(
  train_dataset,
  validation_data=validation_dataset,
  epochs=10
)